#!bin/bash
#!/usr/bin/env bash
# Display 10 "Best School"; on 9th, also say "Hi"
count=1
while [ $count -le 10 ]
do
    echo "Best School"
    if [ $count -eq 9 ]; then
        echo "Hi"
    fi
    count=$((count + 1))
done
